---
platform: linux

resources:
- name: vsm-image
  type: docker-image
  source:
    repository: evasanthan/vsm
    username: evasanthan
    password: vaskala@09
    tag: latest

inputs:
- name: Stateful

outputs:
- name: package-output

run:
  path: Stateful\ci\tasks\package.sh
  args:
  - run source.zip 
