---
resources:
- name: Stateful
  type: git
  source:
    uri: https://github.com/evasanthan/Stateful.git
    branch: master
    username: evasanthan@gmail.com
    password: vaskala09

jobs:
- name: VSM-Analyser
  public: true
  plan:
  - get: Stateful
    trigger: true
  - task: create-source-zip
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: openjdk, tag: 8}
      inputs:
        - name: Stateful
      outputs:
        - name: source-input
      run:
        path: Stateful/ci/tasks/package.sh

  - task: run-vsm-analyser
    params:
      OWNER: evasanthan
    config:
      platform: linux
      image_resource:
         type: docker-image
         source:
           repository: evasanthan/vsm
           username: evasanthan
           password: vaskala09

      inputs:
      - name: source-input
      outputs:
      - name: report-output
      run:
        path: .
        args:
        - run vsm source-input/source.zip
