---
resources:
- name: Stateful
  type: git
  source:
    uri: https://github.com/evasanthan/Stateful.git
    branch: master
    username: evasanthan@gmail.com
    password: vaskala09

jobs:
- name: VSM
  public: true
  serial: true
  plan:
   - get: Stateful
   - task: run
     config:
       platform: linux

       image_resource:
         type: docker-image
         source:
           repository: evasanthan/vsm
           username: evasanthan
           password: vaskala09

       inputs:
       - name: Stateful

       outputs:
       - name: package-output

       run:
        path: Stateful/ci/tasks/package.sh
        args:
        - run package-output/source.zip
