---
resources:
- name: Stateful
  type: git
  source:
    uri: https://github.com/evasanthan/Stateful.git
    branch: master
    username: evasanthan@gmail.com
    password: vaskala09

jobs:
- name: VSM
  public: true
  plan:
  - get: Stateful
  - task: run
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: evasanthan/vsm
