---
resources:
- name: source-git-input
  type: git
  source:
    uri: {{git-url}}
    branch: master
    username: {{git-username}}
    password: {{git-password}}
jobs:
- name: VSM-Analyser
  public: true
  serial: true
  plan:
  - get: source-git-input
  - task: create-source-zip
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: digicloud/java8zip, tag: latest}
      inputs:
        - name: source-git-input
      outputs:
        - name: source-output
      run:
        path: source-git-input/ci/tasks/package.sh

  - task: run-vsm-analyser
    config:
      platform: linux
      image_resource:
         type: docker-image
         source:
           repository: digicloud/vsm
           username: {{dockerhub-username}}
           password: {{dockerhub-password}}
      inputs:
      - name: source-output
      outputs:
      - name: report-output
      run:
        path: /bin/entrypoint.sh
        user: root
        args: [source-output/ 5]
